#Experiment - Data Wangling
#Name - arjit ujjawal

In [ ]:
import pandas as pd
import numpy as np

df1=pd.DataFrame({"C1":[11,21,np.nan], "C2":[12,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  12.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.isna().sum()#columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna()
    #NaN rows are dropped

     C1    C2  C3
0  11.0  12.0  10

In [ ]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     12.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
df1.fillna(df1.mean())

     C1    C2  C3
0  11.0  12.0  10
1  21.0  12.0  20
2  16.0  12.0  30

In [19]:

import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Arjit", "Meera", "Karan", "Bedang"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
print(df)
df.to_csv(("student_data.csv"),index=False)

   Roll No    Name Age Marks Department Admission_Date
0      101    Asha  20    85        CSE     01-06-2023
1      102   Arjit   -    90         IT     03-06-2023
2      103   Meera  21     -        CSE     05-06-2023
3      104   Karan  20    88        cse     07-06-2023
4      105  Bedang  22    76       E&TC       10/06/23

In [20]:
# Step 2: Replace '-' with NaN to mark missing values
import numpy as np

df.replace("-", np.nan, inplace=True)

# Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors='coerce')

'''When converting data (like strings -> datetime),
if some values are invalid or cannot be converted,
instead of throwing an error, it will:
Replace those invalid values with NaT (Not a Time)'''
df

/tmp/ipykernel_152/2444556237.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-", np.nan, inplace=True)

   Roll No    Name   Age  Marks Department Admission_Date
0      101    Asha  20.0   85.0        CSE     01-06-2023
1      102   Arjit   NaN   90.0         IT     03-06-2023
2      103   Meera  21.0    NaN        CSE     05-06-2023
3      104   Karan  20.0   88.0        cse     07-06-2023
4      105  Bedang  22.0   76.0       E&TC       10/06/23

In [21]:
#Step3:check missing values

print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [24]:
# fill missing age with mean
df["Age"].fillna((df["Age"]).mean(),inplace=True)
df

/tmp/ipykernel_152/1217850756.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna((df["Age"]).mean(),inplace=True)

   Roll No    Name    Age  Marks Department Admission_Date
0      101    Asha  20.00   85.0        CSE     01-06-2023
1      102   Arjit  20.75   90.0         IT     03-06-2023
2      103   Meera  21.00    NaN        CSE     05-06-2023
3      104   Karan  20.00   88.0        cse     07-06-2023
4      105  Bedang  22.00   76.0       E&TC       10/06/23

In [26]:
# Fill marks missing with median
df["Marks"].fillna((df["Marks"]).median(),inplace=True)
df

/tmp/ipykernel_152/1946528083.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna((df["Marks"]).median(),inplace=True)

   Roll No    Name    Age  Marks Department Admission_Date
0      101    Asha  20.00   85.0        CSE     01-06-2023
1      102   Arjit  20.75   90.0         IT     03-06-2023
2      103   Meera  21.00   86.5        CSE     05-06-2023
3      104   Karan  20.00   88.0        cse     07-06-2023
4      105  Bedang  22.00   76.0       E&TC       10/06/23

In [28]:
#fix omcpmsostemt text formating
df["Department"] = df["Department"].str.upper()
df

   Roll No    Name    Age  Marks Department Admission_Date
0      101    Asha  20.00   85.0        CSE     01-06-2023
1      102   Arjit  20.75   90.0         IT     03-06-2023
2      103   Meera  21.00   86.5        CSE     05-06-2023
3      104   Karan  20.00   88.0        CSE     07-06-2023
4      105  Bedang  22.00   76.0       E&TC       10/06/23

In [36]:
#covert admiisio date to standard date time format
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors="coerce")
#'''if valur cannot be converted to a valid date , pandas will replace it with NaT(Not a Time) in'''
df

   Roll No    Name    Age  Marks Department Admission_Date
0      101    Asha  20.00   85.0        CSE     2023-01-06
1      102   Arjit  20.75   90.0         IT     2023-03-06
2      103   Meera  21.00   86.5        CSE     2023-05-06
3      104   Karan  20.00   88.0        CSE     2023-07-06
4      105  Bedang  22.00   76.0       E&TC            NaT

In [34]:
#save cleaned data
df.to_csv("cleaned_data_.csv", index=False)
df

   Roll No    Name    Age  Marks Department Admission_Date
0      101    Asha  20.00   85.0        CSE     2023-01-06
1      102   Arjit  20.75   90.0         IT     2023-03-06
2      103   Meera  21.00   86.5        CSE     2023-05-06
3      104   Karan  20.00   88.0        CSE     2023-07-06
4      105  Bedang  22.00   76.0       E&TC            NaT

In [39]:
#upload the datasheet
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [40]:
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [43]:
#imputing the missing value
#1 luggage room
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [48]:
df['AirBags']=df['AirBags'].fillna(value=df['AirBags'].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [49]:
df.to_csv("cleaned_Cars93.csv",index=False)