# Experiment No 11
## Name:Arjit ujjawal
### PRN:25070123142
###Title:Categorical Data Analysis using Python
### Batch:A2

In [ ]:
'''1 Nominal Data
Categories without order
2 Ordinal Data
Categories with order
Common Categorical Data Analysis Methods
Frequency Distribution
'''

In [ ]:
# To Create a Dataset
import pandas as pd
data={
    'Order ID':['01','02','03','04','05','06','07','08','09','10'],
    'Category':['Furniture','Office Supplies','Furniture','Technology','Technology','Furniture','Office Supplies','Technology','Furniture','Technology'],
    'Payment Method':['Cash','Credit Card','Cash','Cash','Credit Card','Cash','Credit Card','Cash','Cash','Credit Card'],
    'Delivery Type':['Standard Class','First Class','Second Class','Express','Second Class','Standard Class','Express','First Class','Standard Class','Standard Class'],
    'Customer Type':['New','Returning','New','Returning','New','Returning','New','Returning','New','Returning']
}
df=pd.DataFrame(data)
df

  Order ID         Category Payment Method   Delivery Type Customer Type
0       01        Furniture           Cash  Standard Class           New
1       02  Office Supplies    Credit Card     First Class     Returning
2       03        Furniture           Cash    Second Class           New
3       04       Technology           Cash         Express     Returning
4       05       Technology    Credit Card    Second Class           New
5       06        Furniture           Cash  Standard Class     Returning
6       07  Office Supplies    Credit Card         Express           New
7       08       Technology           Cash     First Class     Returning
8       09        Furniture           Cash  Standard Class           New
9       10       Technology    Credit Card  Standard Class     Returning

In [ ]:
# Frequency Count
# Count how many orders in each category.
print(df['Category'].value_counts())

Category
Furniture          4
Technology         4
Office Supplies    2
Name: count, dtype: int64

In [ ]:
# Frequency count of Payment Method
print(df['Payment Method'].value_counts())

Payment Method
Cash           6
Credit Card    4
Name: count, dtype: int64

In [ ]:
# Unique values
# Display all unique categories.
print(df['Category'].unique())

['Furniture' 'Office Supplies' 'Technology']

In [ ]:
# Number of Unique Values (nunique)
print(df['Category'].nunique())

3

In [ ]:
# Number of Unique Values (nunique) for Payment Method
print(df['Payment Method'].nunique())

2

In [ ]:
# Cross Tabulation
# Category vs Payment Method
print(pd.crosstab(df['Category'],df['Payment Method']))

Payment Method   Cash  Credit Card
Category
Furniture           4            0
Office Supplies     0            2
Technology          2            2

In [ ]:
# Cross Tabulation (Delivery vs Customer Type)
print(pd.crosstab(df['Delivery Type'],df['Customer Type']))

Customer Type   New  Returning
Delivery Type
Express           1          1
First Class       0          2
Second Class      2          0
Standard Class    2          2

In [ ]:
# Percentage Distribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Furniture          40.0
Technology         40.0
Office Supplies    20.0
Name: proportion, dtype: float64

In [ ]:
# Filtering Data
# Example: Orders from Furniture Cateogry
furniture_orders=df[df['Category']=='Furniture']
print(furniture_orders)

  Order ID   Category Payment Method   Delivery Type Customer Type
0       01  Furniture           Cash  Standard Class           New
2       03  Furniture           Cash    Second Class           New
5       06  Furniture           Cash  Standard Class     Returning
8       09  Furniture           Cash  Standard Class           New

In [ ]:
# Technology Category
technology_orders=df[df['Category']=='Technology']
print(technology_orders)

  Order ID    Category Payment Method   Delivery Type Customer Type
3       04  Technology           Cash         Express     Returning
4       05  Technology    Credit Card    Second Class           New
7       08  Technology           Cash     First Class     Returning
9       10  Technology    Credit Card  Standard Class     Returning

In [ ]:
# Grouping
#Orders by category and payment method
print(df.groupby('Category')['Payment Method'].value_counts())

Category         Payment Method
Furniture        Cash              4
Office Supplies  Credit Card       2
Technology       Cash              2
                 Credit Card       2
Name: count, dtype: int64

In [ ]:
# Sorting Data(Sorted Alphbetically)
sort_df=df.sort_values(by='Category')
print(sort_df)

  Order ID         Category Payment Method   Delivery Type Customer Type
0       01        Furniture           Cash  Standard Class           New
2       03        Furniture           Cash    Second Class           New
5       06        Furniture           Cash  Standard Class     Returning
8       09        Furniture           Cash  Standard Class           New
1       02  Office Supplies    Credit Card     First Class     Returning
6       07  Office Supplies    Credit Card         Express           New
3       04       Technology           Cash         Express     Returning
4       05       Technology    Credit Card    Second Class           New
7       08       Technology           Cash     First Class     Returning
9       10       Technology    Credit Card  Standard Class     Returning

In [ ]:
# Uploading the Dataset
#Upload the Dataset
import pandas as pd
df=pd.read_csv("/Expt11 (1).csv")
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [ ]:
# Count Students in each grade
# Find how many students obtained each grade
print(df['Grade'].value_counts())

Grade
B    24
A    22
C    14
Name: count, dtype: int64

In [ ]:
#2 Percentage Distribution of Grades
print(df['Grade'].value_counts(normalize=True)*100)

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [ ]:
#3 Number of Students in Each Department
print(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [ ]:
#4 Gender Distribution
print(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [ ]:
#5 Gender vs Grade Analysis
print(pd.crosstab(df['Gender'],df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [ ]:
#6 Department vs Gender
print(pd.crosstab(df['Department'],df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [ ]:
#7 Department vs Grade Percentage
print((pd.crosstab(df['Department'],df['Grade'],normalize=True)*100).round(2))

Grade           A      B     C
Department
CSE         21.67   6.67  5.00
ECE          3.33   8.33  6.67
IT          11.67  13.33  5.00
Mechanical   0.00  11.67  6.67

In [ ]:
#8 Grouping Data
print(df.groupby('Department')['Grade'].value_counts())

Department  Grade
CSE         A        13
            B         4
            C         3
ECE         B         5
            C         4
            A         2
IT          B         8
            A         7
            C         3
Mechanical  B         7
            C         4
Name: count, dtype: int64

In [ ]:
#9 Grouping Data (Departmentwise)
print(df.groupby('Department')['Gender'].value_counts())

Department  Gender
CSE         Female    12
            Male       8
ECE         Male       6
            Female     5
IT          Female     9
            Male       9
Mechanical  Male       7
            Female     4
Name: count, dtype: int64